version: '3'
services:
  web:
    build: .
    ports:
      - "80:8000"
    environment:
      - MONGODB_URI=mongodb://root:admin@bot-mongodb-1:27017?retryWrites=true&w=majority
      - LINE_CHANNEL_SECRET=a98764b98b004e53ff56abba03415eab
      - LINE_ACCESS_TOKEN=ENhOCzo9STukJrCaVpvJGhOTDYFvmsJFOz9Jlq9I5tg0aw0vI/GLvDQvosn25UdD/AmavVIM/mAPRrebPGrbOHjsEQt/mkQZONZezgZMk1N/lFjLnEheT5bpI1wWvyXUsUvvfhviUHxBnKkl5RCuAgdB04t89/1O/w1cDnyilFU=
      - NGROK_AUTH_TOKEN=2GFzVAcgpeaDe5iD2Wf5kENWUXk_5xjgozjQe5x23SKgTSVUU
      - USER_ID=U2ccea333afb32dfb430645c0f8e51799
      - LIFF_CHANNEL_SECRET=e153bfa77bc06b2cc8bb8f4e0ff5f62f
    depends_on:
      - mosquitto
      - mongodb
  mosquitto:
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin